- frame/request/authresponse.go
- frame/request/batch.go
- frame/request/execute.go
- frame/request/options.go
- frame/request/prepare.go
- frame/request/query.go
- frame/request/register.go
- frame/request/startup.go
- frame/response/authchallenge.go
- frame/response/authchallenge_test.go
- frame/response/authenticate.go
- frame/response/authsuccess.go
- frame/response/error.go
- frame/response/error_test.go
- frame/response/event.go
- frame/response/event_test.go
- frame/response/ready.go
- frame/response/result.go
- frame/response/result_test.go
- frame/response/supported.go
- frame/response/supported_test.go
All response parse functions are now returning pointer to the structs (#87)
WriteTo and OpCode functions are now called by structure pointers rather than their copies,
removed nolint:gocritic from some WriteTo functions, those were used to silence linter, but
there is no need to use them after most recent fixes (#86)
> frame: added pointers to both request and response

- transport/conn.go
- transport/conn_integration_test.go
- transport/stream.go
- transport/stream_test.go
- moved getting streamID from sendRequest() to setHandler(), as a result
setHandler() changed its return value to (frame.StreamId, err)
- moved stream from Conn to connReader so it's visible in sendRequest()
- added DefaultStreamIDAllocator ported directly from the rust driver
- removed TestStreamIDAllocator, replaced it with the new one in tests.
Fixes #108
> transport: add StreamIDAllocator

- frame/response/supported.go
- frame/response/supported_test.go
- frame/types.go
ScyllaSupported represents Scylla connection options as sent in SUPPORTED frame.
It will be used in f.e. PoolRefiller from issue #112.
> Frame: Added ScyllaSupported

- experiments/atomicbenchmark_test.go
- go.mod
- go.sum
I've benchmarked atomics which we will use in cluster. 
The winner is unsafe pointer.
Benchmark result:
goos: darwin
goarch: amd64
pkg: scylla-go-driver/experiments
cpu: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
BenchmarkLoadAV
BenchmarkLoadAV-8   	691782937	         1.614 ns/op
BenchmarkLoadUP
BenchmarkLoadUP-8   	1000000000	         0.4589 ns/op
PASS
> experiments: Atomic load benchmark - atomic value vs unsafe pointer

- .golangci.yml
Turns out there was a hidden list of issues excluded by default. I turned it off, but errors reported by linter still have to be fixed.
> golangci: turned off default exclusions

- transport/conn.go
- transport/conn_integration_test.go
Idea is based on letting sendRequest() function handle connection closing as it is waiting on a channel and we can use this channel to communicate with it by using errors.
> Conn: send and rcv on error should close connection

- transport/conn.go
I think that setting size to at least 1 does the same job as waiting on channel before entering the inner loop, but it's more elegant 
and simpler.
Fixes #169
> transport: conn, fixed active waiting bug

- transport/conn.go
- transport/conn_integration_bench_test.go
- transport/conn_integration_test.go
- transport/query.go
```
BenchmarkConnQueryIntegration-8             2233           2654839 ns/op            1251 B/op         34 allocs/op
BenchmarkConnAsyncQueryIntegration-8       10000           2088146 ns/op            1289 B/op         11 allocs/op
```
- QueryAsync runs Query in a separated goroutine
- Benchmarks moved to separate file
- connTestHelper added applyFixture
- requestChanSize increased to maxStreamID/2, with 1k goroutines block on putting to the channel
- newQueryForStatement changed to makeQueryForStatement returning Query this removes the gc pressure
> transport: conn, add QueryAsync

- transport/conn.go
- transport/pool.go
- transport/pool_integration_test.go
- transport/query.go
- Added "IO" prefix to errors got by sendRequest caused by connection/internal error to differentiate them from other errors
- UseKeyspace can be called to try change keyspace of every present and future connection in connection pool
Fixes #153
> Transport: Pool, Conn: Added keyspace to conn and refiller

- frame/buffer_fuzz_test.go
- frame/buffer_read.go
- frame/buffer_read_test.go
- frame/buffer_write_test.go
- frame/cqlvalue.go
- frame/cqlvalue_test.go
- frame/request/authresponse_test.go
- frame/request/batch_test.go
- frame/request/execute_test.go
- frame/request/prepare_test.go
- frame/request/query_test.go
- frame/request/register_test.go
- frame/request/startup_test.go
- frame/response/authchallenge_test.go
- frame/response/authenticate_test.go
- frame/response/authsuccess_test.go
- frame/response/error_test.go
- frame/response/event_test.go
- frame/response/result_test.go
- frame/response/supported_test.go
Changes:
```
- added fuzzing for buffer tests
- added fuzzing for cql value tests
- both of those are based on the fact that deserialize(serialize(x)) == x
and they test behaviour for correct input
- added fuzzing for requests and responses
- the last checks if writing and reading frames doesn't cause program to crash
for random data (mostly incorrect input)
- discovered and fixed vulnerability in buffers 'readCopy' method, where
even for corrupted or enormously large int, driver would still try to allocate
slice of given length causing program to crash
```
Fixes #191
> frame: added fuzzing for tests

- .env
- .github/workflows/go.yml
- Makefile
- frame/request/authresponse.go
- frame/request/authresponse_test.go
- frame/response/authchallenge_test.go
- frame/response/authenticate_test.go
- frame/response/authsuccess_test.go
- frame/response/error_test.go
- frame/response/event_test.go
- frame/response/result_test.go
- frame/response/supported_test.go
- transport/cluster.go
- transport/cluster_integration_test.go
- transport/conn.go
- transport/conn_integration_test.go
- transport/pool_integration_test.go
In gocql and rust they only supported  **PasswordAuthenticator** and used it no matter what approved authenticator was sent in **Authenticate** response.
Do we also only care for this one?
Fixes #105
> transport: added support for authentication

- experiments/cmd/benchtab/config.go
- experiments/cmd/benchtab/main.go
Async mode was broken - test would never end.
The root cause was copying `nextBatchStart int64` to massAsyncQuery and then getting the address of it.
This patch contains a refactoring
* massAsyncQuery is inlined
* massAsyncXXX is renamed to asyncXXX
* batch-size can be set from command line
> cmd/benchtab: fix async mode

- transport/cluster.go
- transport/node.go
- transport/policy.go
- transport/policy_test.go
This pull request replaces BTree with a sorted slice recalculated on topology refresh, replicas are found using binary search. This removes function allocations regarding BTree filter functions.
It also brings back node duplicate check in SimpleStrategy as a single node can appear multiple times in a row on the token ring, example:
```
3 node cluster, keyspace with RF=2
nodetool ring testks output:
Datacenter: DC1
==========
Address     Rack        Status State   Load            Owns                Token                                       
9206783188564719566   
...
172.18.0.2  Rack1       Up     Normal  238.6 KB        66.66%              8015852181688326448                         
172.18.0.4  Rack1       Up     Normal  234.83 KB       66.48%              8048433568933139078 …
```
> cluster: replaced btree with sorted cyclic slice

- query.go
- session.go
- transport/cluster.go
- transport/cluster_integration_test.go
- transport/node.go
- transport/policy.go
- transport/policy_test.go
- transport/trie.go
- removed wrapping of policies
- policy interface is now just Node(QueryInfo, n int), which returns the n-th node of the plan
- created policyInfo struct with Preprocess() method, meant to be called on topology refresh
to allow calculating all possible query plans in advance,
its passed to the policy inside QueryInfo for further use.
> transport: added preprocessed policies

- frame/buffer.go
- frame/types.go
- go.mod
- go.sum
- query.go
- session.go
- transport/compress.go
- transport/compress_test.go
- transport/conn.go
- transport/conn_integration_test.go
- ConnReader can now decompress frame body on recv()
- Added support for snappy and lz4
Fixes #106
> Transport: Compression added

- session.go
- session_integration_test.go
- transport/cluster.go
- transport/node.go
- transport/policy.go
- transport/policy_test.go
Prepare now prepares on all nodes, once per node, as sources suggest:
https://github.com/apache/cassandra/blob/adcff3f630c0d07d1ba33bf23fcb11a6db1b9af1/doc/native_protocol_v4.spec#L738-L740
https://github.com/scylladb/scylladb/blob/4d24097b4b86d484159c011f46b9e43268d342d1/transport/server.cc#L941-L950
Also made the driver fallback from token aware policy to round robin
if both session keyspace and query keyspace are unspecified, this is a temporary fix until #257 is resolved.
> session: prepare now prepares on all nodes

- experiments/cmd/benchtab/main.go
- query.go
- session.go
- session_integration_bench_test.go
- session_integration_test.go
- transport/cluster.go
- transport/cluster_integration_test.go
- transport/compress.go
- transport/compress_test.go
- transport/conn.go
- transport/conn_integration_test.go
- transport/node.go
- transport/pool.go
- transport/pool_integration_test.go
This PR changes NewSession, Session.Prepare, Query.Execute, Query.AsyncExecute to take context.Context as an argument.
Context passed to NewSession forces it to close on context cancellation, this is done by:
- checking ctx.Done() in cluster.loop and closing the cluster if ctx is cancelled
- checking if context is cancelled in OpenConn, preventing dialing after context cancellation.
- preventing topology refresh if context is cancelled, and during refresh in calls to openConnPool preventing opening new pools.
NewSession's context also stops requests from being sent to server in connWriter.send after cancellation,
contexts passed to Session.Prepare, Query.Execute, Query.AsyncExecute provide the same behaviour.
Context's cancellation is also checked right before allocating requests …
> api: use contexts

- .env
- docker-compose.yml
- query.go
- session.go
- session_integration_test.go
- testdata/config/scylla.yaml
- transport/node.go
- transport/query.go
This PR adds the ability of checking and awaiting schema agreement by calling adequate methods on Session and Node.
Schema agreement is checked by checking if all nodes have the same schema_version in system.local table, same as in https://github.com/scylladb/scylla-rust-driver/pull/250
It also makes the driver await schema agreement automatically after queries changing schema:
Paraphrasing https://github.com/scylladb/scylla-rust-driver/pull/460
>Now, the session automatically waits for schema agreement after
>executing a statement which modifies the schema. The rationale for this
>change is that, previously, it was the user's responsibility to wait for
>schema agreement and it was easy to forget about this check.
>
>The automatic wait for schema agreement is never a bug, although it can …
> Wait for schema agreement automatically

- frame/response/error.go
- query.go
- session.go
- session_integration_test.go
- transport/conn.go
- transport/node.go
- transport/query.go
The goal of this PR is to make normal and paged queries use the retry policy implented in #225.
RetryDecider implemented in #225 provides a Decide() method that for a error response will return a decision from list:
- DontRetry
- RetrySameNode
- RetryNextNode
In this PR I changed query.Exec() and query.Iter() to use this retry decider to iterate over the node plan generated by
the HostSelectionPolicy. 
The goal of the integration test implemented in this PR is to check if the actions performed by the driver match the Retry Policy decisions, and if using the Default Retry Policy produces the right amount of retries.
In the case of normal queries, a RetryDecider is allocated after the first try fails, avoiding unnecessary allocation in most cases.
In paged queries I added the needed fields …
> query: use retry policy

- .github/workflows/go.yml
- Makefile
The goal of this PR is to run integration tests on the cluster described by docker-compose.yml in GH workflows.
It extends the Makefile with ability to run integration tests in docker, this is used by the modified workflow.
This PR also resolves a small bug in OpenShardConn, when context is done, instead of immediate return from the function, it would try all ports as connections wouldn't open due to context being done, bloating the integration test log with thousands of lines.
> Run integration tests in Github Workflows

- transport/routing.go
- transport/routing_test.go
There was an overflow in ShardPortIterator, leading the driver sometimes to dial from source ports outside of range specified in routing.go by minPort and maxPort, trying dialing from reserved ports. Also this overflow can make the driver pick a source port that doesn't correspond to the queried shard.
This PR removes this overflow, and adds a test checking for correct behavior of ShardPortIterator.
> transport: fixed an overflow in ShardPortIterator

- query.go
- session.go
- transport/cluster.go
- transport/cluster_integration_test.go
- transport/conn.go
- transport/node.go
- transport/pool.go
- transport/pool_integration_test.go
The goal of this PR is to resolve two intertwined issues:
-  #279 
The problem here was that on initial discovery of a node, if it was down it's pool couldn't be initialized, leaving it as nil.
When a topology refresh happens, the driver was reusing the pool without checking if it actually exists.<br>
For this problem the proposed solution is to move the node's connection pool and status initialization to the Node, instead of managing it inside cluster, calling node.Init() in places where the node could have status UP to ensure we have working connections to this node.
-  #222 
This issue comes with two problems: pool being nil from reasons mentioned above, and pool returning nil connections, as the node may be down, or a shard connection is missing.<br>
The proposed solution is to …
> transport: avoid nil pointer dereferencing

- log/logger.go
- session.go
- session_integration_test.go
- transport/cluster.go
- transport/conn.go
- transport/conn_integration_test.go
- transport/node.go
- transport/observer.go
- transport/policy.go
- transport/policy_test.go
- transport/pool.go
- transport/pool_integration_test.go
This PR provides a Logger interface allowing to supply
a custom logger as part of (Session)ConnConfig.
It also provides three implementations of Logger:
- DefaultLogger, logging only warnings
- DebugLogger, logging everything that can be useful for debugging,
it is used by default in tests
- NopLogger, logging nothing
Fixes #271
> session: allow log configuration using Logger interface.
